// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromillePartner_BackEnd.Data;

#nullable disable

namespace PromillePartner_BackEnd.Migrations
{
    [DbContext(typeof(VoresDbContext))]
    [Migration("20241211112038_timestamp")]
    partial class timestamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PromillePartner_BackEnd.Models.DrinkPlan", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("TimeStamp")
                        .HasColumnType("bigint");

                    b.HasKey("Identifier");

                    b.ToTable("DrinkPlan");
                });

            modelBuilder.Entity("PromillePartner_BackEnd.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Man")
                        .HasColumnType("bit");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PromillePartner_BackEnd.Models.PiReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Promille")
                        .HasColumnType("float");

                    b.Property<long>("TimeStampMiliseconds")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PiReadings");
                });

            modelBuilder.Entity("PromillePartner_BackEnd.Models.PromillePartnerPi", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identifier");

                    b.ToTable("PromillePartnerPi");
                });

            modelBuilder.Entity("PromillePartner_BackEnd.Models.UpdateDrinkPlanData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DrinkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrinkPlanIdentifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("TimeDifference")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("DrinkPlanIdentifier");

                    b.ToTable("UpdateDrinkPlanData");
                });

            modelBuilder.Entity("PromillePartner_BackEnd.Models.UpdateDrinkPlanData", b =>
                {
                    b.HasOne("PromillePartner_BackEnd.Models.DrinkPlan", null)
                        .WithMany("DrinkPlanen")
                        .HasForeignKey("DrinkPlanIdentifier");
                });

            modelBuilder.Entity("PromillePartner_BackEnd.Models.DrinkPlan", b =>
                {
                    b.Navigation("DrinkPlanen");
                });
#pragma warning restore 612, 618
        }
    }
}
